# Downloads the self-hosted webfonts used by FLASHORA (Google Fonts, OFL licensed)
# and writes src/styles/fonts.css with local @font-face rules.
$ErrorActionPreference = "Stop"
$root = Split-Path -Parent $PSScriptRoot
$fontDir = Join-Path $root "public\fonts"
$cssPath = Join-Path $fontDir "fonts.css"
New-Item -ItemType Directory -Force -Path $fontDir | Out-Null
New-Item -ItemType Directory -Force -Path (Join-Path $root "src\styles") | Out-Null

$ua = "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36"
$spec = "https://fonts.googleapis.com/css2?family=Inter:wght@400..700&family=Space+Grotesk:wght@500..700&display=swap"

$css = (Invoke-WebRequest -Uri $spec -Headers @{ "User-Agent" = $ua } -UseBasicParsing -TimeoutSec 40).Content

# Keep only the latin subset faces (covers English + French accents).
$blocks = [regex]::Matches($css, "(?s)/\*\s*(?<sub>[a-z0-9-]+)\s*\*/\s*(?<face>@font-face\s*\{.*?\})")
$out = @()
$cache = @{}
$idx = 0
foreach ($b in $blocks) {
  if ($b.Groups["sub"].Value -ne "latin") { continue }
  $face = $b.Groups["face"].Value
  $url = [regex]::Match($face, "url\((?<u>[^)]+)\)").Groups["u"].Value.Trim("'", '"')
  if (-not $url) { continue }
  $family = [regex]::Match($face, "font-family:\s*'(?<f>[^']+)'").Groups["f"].Value
  $weight = [regex]::Match($face, "font-weight:\s*(?<w>[^;]+)").Groups["w"].Value
  $key = $url
  if (-not $cache.ContainsKey($key)) {
    $idx++
    $slug = ($family.ToLower() -replace '\s+', '-') + "-latin.woff2"
    $file = Join-Path $fontDir $slug
    Invoke-WebRequest -Uri $url -Headers @{ "User-Agent" = $ua } -OutFile $file -TimeoutSec 40 -UseBasicParsing
    $cache[$key] = $slug
    Write-Output "font: $family $weight -> $slug ($((Get-Item $file).Length) bytes)"
  }
  $local = $cache[$key]
  # Relative to public/fonts/fonts.css so it works from dev, dist and file://
  $face = [regex]::Replace($face, "url\([^)]+\)\s*format\('woff2'\)", "url('$local') format('woff2')")
  $out += $face
}

$header = "/* FLASHORA self-hosted fonts (Google Fonts / SIL Open Font License) - generated by scripts/fetch-fonts.ps1 */`n"
Set-Content -Path $cssPath -Value ($header + ($out -join "`n")) -Encoding UTF8
Write-Output "wrote $cssPath ($($out.Count) faces)"
